-- MySQL Script generated by MySQL Workbench
-- 07/11/16 16:45:38
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema baseReservaRestaurante
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema baseReservaRestaurante
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `baseReservaRestaurante` DEFAULT CHARACTER SET utf8 ;
USE `baseReservaRestaurante` ;

-- -----------------------------------------------------
-- Table `baseReservaRestaurante`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `baseReservaRestaurante`.`Persona` (
  `idPersona` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(20) NOT NULL,
  `aPaterno` VARCHAR(45) NOT NULL,
  `aMaterno` VARCHAR(20) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(10) NOT NULL,
  `foto` VARCHAR(10) NULL,
  `huellaBiometrica` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idPersona`),
  UNIQUE INDEX `foto_UNIQUE` (`foto` ASC),
  UNIQUE INDEX `huellaBiometrica_UNIQUE` (`huellaBiometrica` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `baseReservaRestaurante`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `baseReservaRestaurante`.`Cliente` (
  `idPersona` INT NOT NULL,
  `codigo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPersona`),
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC),
  CONSTRAINT `fk_persona_cliente`
    FOREIGN KEY (`idPersona`)
    REFERENCES `baseReservaRestaurante`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `baseReservaRestaurante`.`Almuerzo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `baseReservaRestaurante`.`Almuerzo` (
  `idAlmuerzo` INT NOT NULL AUTO_INCREMENT,
  `costoAlmuerzo` DECIMAL(4,2) NOT NULL,
  `tipo` VARCHAR(25) NOT NULL,
  `Descripción` VARCHAR(255) NULL,
  PRIMARY KEY (`idAlmuerzo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `baseReservaRestaurante`.`Registro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `baseReservaRestaurante`.`Registro` (
  `idRegistro` INT NOT NULL AUTO_INCREMENT,
  `idCliente` INT NOT NULL,
  `idAlmuerzo` INT NOT NULL,
  `costoTotal` DECIMAL(4,2) NOT NULL,
  `nroAlmuerzosReservados` INT NOT NULL,
  `nroAlmuerzosConsumidos` INT NOT NULL,
  `estadoReserva` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idRegistro`),
  INDEX `fk_reserva_cliente_idx` (`idCliente` ASC),
  INDEX `fk_reserva_almuerzo_idx` (`idAlmuerzo` ASC),
  CONSTRAINT `fk_reserva_cliente`
    FOREIGN KEY (`idCliente`)
    REFERENCES `baseReservaRestaurante`.`Cliente` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reserva_almuerzo`
    FOREIGN KEY (`idAlmuerzo`)
    REFERENCES `baseReservaRestaurante`.`Almuerzo` (`idAlmuerzo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
